=== kmafeni04/ssdg/conf.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "https://example.com/schemas/dirconfig.schema.json",
  "title": "DirConfig",
  "type": "object",
  "properties": {
    "input_dir": {
      "type": "string"
    },
    "output_dir": {
      "type": "string"
    },
    "ext": {
      "type": "string"
    },
    "lang": {
      "type": "string"
    },
    "lead": {
      "type": "string"
    },
    "single_line": {
      "type": "string"
    },
    "multi_line": {
      "$ref": "#/$defs/Block"
    },
    "code_block": {
      "$ref": "#/$defs/Block"
    },
    "ignore_block": {
      "$ref": "#/$defs/Block"
    },
    "ignore": {
      "type": "array",
      "items": {
        "type": "string"
      }
    }
  },
  "required": [
    "input_dir",
    "output_dir",
    "ext",
    "lang",
    "single_line",
    "multi_line"
  ],
  "$defs": {
    "Block": {
      "type": "object",
      "properties": {
        "starting": {
          "type": "string"
        },
        "ending": {
          "type": "string"
        }
      },
      "required": [
        "starting",
        "ending"
      ]
    }
  }
}

=== kmafeni04/ssdg/conf.json
{
  "$schema": "./conf.schema.json",
  "input_dir": "./test",
  "output_dir": "docs",
  "ext": "nelua",
  "lang": "lua",
  "lead": "-",
  "single_line": "--",
  "multi_line": {
    "starting": "--[[",
    "ending": "]]"
  },
  "code_block": {
    "starting": "`",
    "ending": "`"
  },
  "ignore_block": {
    "starting": "|",
    "ending": "|"
  },
  "ignore": []
}
